version: '3.8'

services:
  wormhole:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data
      - ./bls_keypair.keypair:/usr/src/app/bls_keypair.keypair
    working_dir: /usr/src/app
    command: cargo run
    ports:
      - "8080:8080"
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
      - 4318:4318