version: '3.8'

services:
  wormhole-operator:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
      - ./data:/usr/src/app/data
      - ./bls_keypair.keypair:/usr/src/app/bls_keypair.keypair
    working_dir: /usr/src/app
    command: cargo run
    ports:
      - "8080:8080"
      - "3000:3000"
      - "9000:9000"
  
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - operator